# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user', '0002_auto_20180925_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ImageField(upload_to='user/%Y%m%d', verbose_name='用户头像')),
            ],
        ),
    ]
