# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user', '0003_testimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='head',
            field=models.ImageField(default='user/201809/25/1.jpg', upload_to='head/%Y/%m', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='testimagemodel',
            name='head',
            field=models.ImageField(upload_to='user/%Y%m/%d', verbose_name='用户头像'),
        ),
    ]
