# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0002_auto_20180926_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityzone',
            options={'verbose_name': '活动专区管理', 'verbose_name_plural': '活动专区管理'},
        ),
    ]
